name: nyc_airbnb
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.28.0
  - pyyaml=6.0
  - hydra-core=1.2.0
  - pip=22.1.2
  - pip:
      - wandb==0.13.2
      - hydra-joblib-launcher==1.2.0
