name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.4
  - pip=22.1.2
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - matplotlib=3.5.2
  - pillow=9.2.0
  # - hydra-core=1.2.0
  - pip:
      - wandb==0.13.2
      # - hydra-joblib-launcher==1.2.0
